apiVersion: v1
kind: Service
metadata:
  name: buged-php
  namespace: default
  labels:
    app: buged-php
spec:
  type: NodePort
  selector:
    app: buged-php
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
