apiVersion: v1
kind: Namespace
metadata:
  name: {{K8S_NAMESPACE}}
  labels:
    name: {{K8S_NAMESPACE}}
    managed-by: jenkins
  annotations:
    description: "Namespace for {{K8S_NAMESPACE}} application deployment"
