apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  namespace: {{K8S_NAMESPACE}}
  labels:
    app: {{APP_NAME}}
  annotations:
    description: "External access to {{APP_NAME}} application"
spec:
  type: NodePort
  selector:
    app: {{APP_NAME}}
  ports:
  - port: 80
    targetPort: {{APP_PORT}}  # Container runs on non-privileged port
    protocol: TCP
    name: http
